final List<String> keywords = [
  'who are you',
  'hello',
  'morning',
  'afternoon',
  'evening',
  'how are you',
  'name',
  'what can you do',
  'joke',
  'thank you',
  'bye',
  'how to find love',
  'tell me about relationships',
  'dating',
  'do you believe in love',
  'how to build confidence',
  'what are red flags in dating',
  'what is love',
  'how to impress someone',
  'soulmate',
  'how to handle a breakup',
  'what are green flags',
  'how to apologize',
  'what is flirting',
  'how to start a conversation',
  'how to know if someone likes you',
  'is online dating good',
  'tell me a pickup line',
  'how to trust someone',
  'what makes a good partner',
  'how to deal with jealousy',
  'how to stay motivated',
  'what are healthy boundaries',
  'how to plan a perfect date',
  'what is chemistry in love',
  'how to build trust in a relationship',
  'what makes someone attractive',
  'how to deal with rejection',
  'how to know if it’s love or infatuation',
  'how to communicate better',
  'how to handle long-distance relationships',
  'what is unconditional love',
  'how to deal with insecurity',
  'how to keep a relationship exciting',
  'what are deal breakers in relationships',
  'how to express love',
  'how to move on',
  'can opposites attract',
  'what is emotional compatibility',
  'how to be a good listener',
  'how to handle disagreements',
  'when is the right time to say I love you',
  'what are signs of a healthy relationship',
  'how to handle loneliness',
  'what is emotional intimacy',
  'how to manage anger',
  'how to deal with heartbreak',
  'why do I feel insecure',
  'how to boost self-esteem',
  'what is emotional maturity',
  'how to express emotions',
  'why do people fall out of love',
  'how to forgive someone',
  'how to handle emotional pain',
  'what are healthy coping mechanisms',
  'why do I overthink',
  'how to let go of the past',
  'how to feel more confident',
  'what is self-love',
  'how to build emotional resilience',
  'why do people ghost',
  'how to stay emotionally connected',
  'how to handle emotional burnout'
];

final List<String> responses = [
  'I am Libby, here to assit with any questions relating to the app',
  'Hello, is good to have you here',
  'Hi!, Good Morning \nHow can I assist you today?',
  'Good Afternoon,\nHope you are having a great day\n How can I assist you?',
  'Hi, good evening,\nI trust your day was awesome\nHow can I assist you?',
  'I am just a bot, but I am doing great! How about you?',
  'I am your friendly assistant. You can call me Chatmate!',
  'I can help you with questions, give advice, or simply chat. What do you need?',
  'Why don’t scientists trust atoms? Because they make up everything! 😂',
  'You’re welcome! Let me know if there’s anything else I can do for you.',
  'Goodbye! Take care and come back soon.',
  'Finding love starts with loving yourself. Be genuine and open to new experiences.',
  'Relationships require communication, trust, and effort. Start with friendship and let it grow.',
  'Dating is about getting to know someone better to see if you share a connection.',
  'As a bot, I believe in love as a concept. What about you?',
  'Confidence comes from self-belief. Focus on your strengths and take one step at a time.',
  'Red flags can include dishonesty, lack of respect, and controlling behavior. Trust your instincts!',
  'Love is a deep affection, care, and connection with someone. It’s unique for everyone!',
  'Be confident, genuine, and attentive. Showing respect and being yourself goes a long way.',
  'A soulmate is someone you deeply connect with, often in ways that feel natural and effortless.',
  'Breakups are tough. Give yourself time to heal, focus on self-care, and seek support if needed.',
  'Green flags include kindness, honesty, good communication, and respect for your boundaries.',
  'A sincere apology includes admitting your mistake, showing you’re sorry, and working to improve.',
  'Flirting is playful, subtle, and respectful communication that shows interest in someone.',
  'Start with a compliment or a friendly question, like “What’s your favorite hobby?”',
  'Signs include frequent attention, engaging conversations, and showing genuine interest in your life.',
  'Online dating can be great if done safely. Be cautious and take your time to get to know someone.',
  'Here’s a pickup line: “Are you a magician? Because every time I look at you, everyone else disappears!”',
  'Trust takes time. Look for consistency in actions and words, and communicate openly.',
  'A good partner supports you, communicates well, respects you, and makes you feel valued.',
  'Jealousy happens, but focus on communication and self-reflection to address the root cause.',
  'Motivation comes from setting clear goals, celebrating small wins, and staying consistent.',
  'Healthy boundaries mean knowing your limits and communicating them with respect.',
  'A perfect date depends on knowing the other person’s interests. Keep it thoughtful and fun!',
  'Chemistry in love is the spark or connection that makes two people feel drawn to each other.',
  'Building trust takes time, honesty, and consistent actions. Communication is key!',
  'Attractiveness is subjective but includes confidence, kindness, and a positive attitude.',
  'Rejection can be tough. Remember, it’s not personal. Learn from it and move forward.',
  'Love is deep and selfless, while infatuation is intense but often short-lived.',
  'Effective communication means listening, being honest, and expressing your feelings clearly.',
  'Long-distance relationships thrive on trust, communication, and making time for each other.',
  'Unconditional love is loving someone without expectations or conditions.',
  'Insecurity can be managed by focusing on self-worth and openly discussing feelings with your partner.',
  'Keep the spark alive by trying new activities, sharing surprises, and staying curious about each other.',
  'Deal breakers vary but can include dishonesty, lack of respect, or incompatible values.',
  'Express love through kind actions, words of affirmation, quality time, and physical affection.',
  'Moving on takes time. Focus on self-growth, lean on friends, and allow yourself to heal.',
  'Yes, opposites can attract, but mutual respect and shared values often make it work long-term.',
  'Emotional compatibility means understanding, supporting, and respecting each other’s feelings.',
  'Being a good listener means giving full attention, avoiding interruptions, and showing empathy.',
  'Handle disagreements by staying calm, focusing on the issue, and avoiding personal attacks.',
  'Loneliness can be tough. Try connecting with others, exploring new hobbies, or focusing on self-care.',
  'Emotional intimacy is sharing your innermost thoughts and feelings with someone you trust.',
  'Managing anger involves deep breathing, stepping away from triggers, and finding constructive outlets.',
  'Heartbreak takes time to heal. Surround yourself with support and focus on self-growth.',
  'Insecurity often stems from self-doubt. Reflect on your strengths and practice self-compassion.',
  'Boost self-esteem by setting small goals, celebrating achievements, and surrounding yourself with positivity.',
  'Emotional maturity means managing feelings responsibly and understanding others’ perspectives.',
  'Expressing emotions involves being honest with yourself and using “I feel” statements to communicate.',
  'People may fall out of love due to a lack of connection, effort, or compatibility over time.',
  'Forgiving someone is about releasing the burden of resentment for your own peace of mind.',
  'Emotional pain lessens with time. Journaling, therapy, or talking to someone you trust can help.',
  'Healthy coping includes exercise, mindfulness, creative outlets, and seeking support when needed.',
  'Overthinking happens when we overanalyze. Ground yourself in the present and challenge negative thoughts.',
  'Letting go of the past means accepting it, learning from it, and focusing on your present and future.',
  'Confidence grows with practice. Celebrate small successes and challenge yourself to step out of your comfort zone.',
  'Self-love is appreciating and accepting yourself, flaws and all. Treat yourself kindly and set boundaries.',
  'Building resilience involves practicing mindfulness, self-care, and focusing on your inner strengths.',
  'People ghost for many reasons, often due to fear of confrontation or lack of interest. It reflects on them, not you.',
  'Stay emotionally connected by actively listening, sharing your feelings, and spending quality time together.',
  'Emotional burnout is real. Rest, take breaks, and engage in activities that recharge your mind and heart.'
];
